version: '3.8'

services:
  web:
    build: .
    ports:
      - "8100:8000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - REDIS_URL=redis://redis:6380/0
    depends_on:
      - redis
    volumes:
      - .:/src

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: